### ISSUE TITLE
Add terms and conditions block.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/Magento-2-Latest#13]
Error trying to order with Payment Action: Order whilst site has Terms and Conditions to check.

```The order wasn't placed. First, agree to the terms and conditions, then try placing your order again.```

```
#0 vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/GuestValidation.php(78): Magento\\CheckoutAgreements\\Model\\Checkout\\Plugin\\GuestValidation->validateAgreements(Object(Magento\\Quote\\Model\\Quote\\Payment))
#1 vendor/magento/framework/Interception/Interceptor.php(121): Magento\\CheckoutAgreements\\Model\\Checkout\\Plugin\\GuestValidation->beforeSavePaymentInformationAndPlaceOrder(Object(Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor), '...', '...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))
#2 vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}('...', '...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))
#3 generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(26): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#4 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder('...', '...', Object(Magento\\Quote\\Model\\Quote\\Payment), Object(Magento\\Quote\\Model\\Quote\\Address))
#5 vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#6 vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))
#7 vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
#8 vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)
#9 vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))
#10 generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)
#11 vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
#12 generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()
#13 vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()
#14 pub/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))
#15 {main}"
```

Solution: put under billing address block.
view/frontend/web/template/payment/laybuy.html:43
```html
        <div class="checkout-agreements-block">
            <!-- ko foreach: $parent.getRegion('before-place-order') -->
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
            <!--/ko-->
        </div>
```

**Comment by drevidchuck** [comment]
Hello Liam
Thanks for reporting this issue
These is now fixed in https://github.com/Laybuy/Magento-2-Latest/commit/15a9a5e16810b2cb8ce0820d0a6abdb22c61797f
